Repository Tteonaso/Tteonaso-Frontend, pull requests merged in 2024-11, with the labels that each got.

#2 Feature/directory #1 기본 디렉토리 구조 설정
  .gitignore
  README.md
  index.html
  package-lock.json
  package.json
  public/.gitkeep
  public/favicon.ico
  src/App.vue
  src/api/.gitkeep
  src/assets/base.css
  src/assets/css/main.css
  src/assets/fonts/BMDOHYEON_ttf.ttf
  src/assets/fonts/BMHANNAAir_ttf.ttf
  src/assets/fonts/BMHANNAPro.ttf
  src/assets/fonts/BMJUA_ttf.ttf
  src/assets/fonts/BMYEONSUNG_ttf.ttf
  src/assets/images/tteonaso.png
  src/assets/logo.svg
  src/common/.gitkeep
  src/components/HelloWorld.vue
  src/components/TheWelcome.vue
  src/components/WelcomeItem.vue
  src/components/icons/IconCommunity.vue
  src/components/icons/IconDocumentation.vue
  src/components/icons/IconEcosystem.vue
  src/components/icons/IconSupport.vue
  src/components/icons/IconTooling.vue
  src/components/map/KaKaoMap.vue
  src/layouts/.gitkeep
  src/main.js
  src/middlewares/.gitkeep
  src/plugins/.gitkeep
  src/router/.gitkeep
  src/services/.gitkeep
  src/store/.gitkeep
  src/views/.gitkeep
Labels: Feat

#5 Feat/#4 on boarding sign up in
  package-lock.json
  package.json
  src/App.vue
  src/assets/css/main.css
  src/components/member/OnBoarding.vue
  src/components/member/SignIn.vue
  src/components/member/SignUp.vue
  src/main.js
  src/router/index.js
Labels: Feat

#6 Feature/MapFilter/ #3 임시 지도 필터 저장
  index.html
  src/App.vue
  src/assets/css/global.css
  src/assets/css/map/filter.css
  src/components/map/KaKaoMap.vue
  src/components/map/MapFilter.vue
  src/main.js
  src/router/.gitkeep
  src/router/index.js
  src/views/.gitkeep
  src/views/HomePage.vue
  vite.config.js
Labels: Feat

#8 Feat/#7-Alarm-Modal
  src/components/member/SignIn.vue
  src/components/member/SignUp.vue
  src/layouts/Modal.vue
Labels: Feat

#11 Feat/#9 chat list vue
  package-lock.json
  package.json
  src/assets/images/ArrowLeft.png
  src/assets/images/ArrowRight.png
  src/assets/images/Chat.png
  src/assets/images/Explore.png
  src/assets/images/Settings.png
  src/assets/images/chatIcon.png
  src/assets/images/searchIcon.png
  src/components/BottomNavigationBar.vue
  src/components/chatroom/ChatRoom.vue
  src/components/chatroom/ChatRoomList.vue
  src/components/chatroom/SearchBar.vue
  src/router/index.js
  src/views/ChatRoomListPage.vue
Labels: Feat

#14 Feat/#13 chatting vue
  src/assets/images/Send.png
  src/components/chatroom/ChatRoom.vue
  src/components/chatroom/ChatRoomList.vue
  src/router/index.js
  src/views/ChatPage.vue
Labels: Feat

#17 Feat/#15 jwt token and after login
  package-lock.json
  package.json
  src/components/chatroom/ChatRoom.vue
  src/components/chatroom/ChatRoomList.vue
  src/components/member/SignIn.vue
  src/main.js
  src/store/user.js
  src/views/ChatPage.vue
  src/views/ChatRoomListPage.vue
Labels: Feat

#21 Feat/#20-Font-Family
  src/components/BottomNavigationBar.vue
  src/components/chatroom/ChatRoom.vue
  src/components/chatroom/SearchBar.vue
  src/components/member/OnBoarding.vue
  src/components/member/SignIn.vue
  src/components/member/SignUp.vue
  src/layouts/Modal.vue
  src/views/ChatPage.vue
  src/views/ChatRoomListPage.vue
Labels: Style

#23 Feature/AI-Travel/#22 AI 여행 설계 스타일 변경
  src/assets/images/loading.gif
  src/components/gpt-schedule/Recommendation.vue
Labels: Style

#25 Feat/#24-Search-ChatRoom
  src/components/chatroom/ChatRoomList.vue
  src/views/ChatRoomListPage.vue
Labels: Feat

#26 Feature/Gpt-Schedule/#22. AI 일정 계획 페이지 스타일 추가
  src/assets/css/map/search.css
  src/assets/images/loading.gif
  src/components/gpt-schedule/Question.vue
  src/components/gpt-schedule/Recommendation.vue
  src/components/gpt-schedule/Survey.vue
Labels: Style

#28 Feat/#27 update member info
  src/components/member/Update.vue
  src/router/index.js
  src/views/member/SettingPage.vue
Labels: Feat

#30 Fix/#29-Update-Member-Info
  src/components/member/Update.vue
  src/views/chat/ChatPage.vue
Labels: Fix
